version: "3.9"
services:
  animals-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - animals-db
    volumes:
      - .:/home/app
  animals-db:
    image: mongo
    ports:
      - "3005:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=luis
      - MONGO_INITDB_ROOT_PASSWORD=2002
    volumes:
      - mongo-data:/data/db
      # mysql => /var/lib/mysql
      # postgres => /var/lib/postgresql/data

volumes:
  mongo-data:
